### ISSUE TITLE
FrescoImage crashing with Compose beta 07

### ISSUE THREAD

**Issue by mrmans0n** [skydoves/Landscapist#23]
**Please complete the following information:**
- Library Version [v1.2.1]
- Affected Device(s) [e.g. Pixel 4 XL]
 
**Describe the Bug:**

After updating the compose dependency to `1.0.0-beta07`, FrescoImage usages crash at runtime with this stacktrace:
```
05-19 10:09:28.796 29352 29352 E AndroidRuntime: FATAL EXCEPTION: main
05-19 10:09:28.796 29352 29352 E AndroidRuntime: Process: com.twitter.sandbox.uiarch, PID: 29352
05-19 10:09:28.796 29352 29352 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer; in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~xzvvhkZTNhoZWKRPq8VHJg==/com.twitter.sandbox.uiarch-W3sSHxog8MH9aWO23m7A6A==/base.apk)
05-19 10:09:28.796 29352 29352 E AndroidRuntime: 	at com.skydoves.landscapist.fresco.FrescoImage__FrescoImageKt.FrescoImage(FrescoImage.kt:85)
05-19 10:09:28.796 29352 29352 E AndroidRuntime: 	at com.skydoves.landscapist.fresco.FrescoImage.FrescoImage(FrescoImage.kt:1)
05-19 10:09:28.796 29352 29352 E AndroidRuntime: 	at com.twitter.sandbox.uiarch.samples.dogs.DogContentViewProviderKt.ShowDog(DogContentViewProvider.kt:136)
```

And this is the calling code:

```
    Row(modifier = Modifier.clickable { viewModel.loadNewDog() }) {
        FrescoImage(imageUrl = dogImage.url, modifier = Modifier.fillMaxSize(), contentScale = ContentScale.Fit)
    }
```

**Expected Behavior:**

Using FrescoImage should not cause a runtime crash.

**Comment by skydoves** [comment]
Hi @mrmans0n,
Would you test using a SNAPSHOT version `1.2.2-SNAPSHOT`?
For importing the SNAPSHOT in your project, add the below code.

```gradle
repositories {
   maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by masterofdaemon** [comment]
> 
> 
> Hi @mrmans0n,
> Would you test using a SNAPSHOT version `1.2.2-SNAPSHOT`?
> For importing the SNAPSHOT in your project, please add the below code.
> 
> ```groovy-gradle
> repositories {
>    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
> }
> ```

how can i use it in gradle.kts?

**Comment by skydoves** [comment]
maven(url = "https://oss.sonatype.org/content/repositories/snapshots/"

**Comment by masterofdaemon** [comment]
> 
> 
> ```groovy-gradle
> maven(url = "https://oss.sonatype.org/content/repositories/snapshots/")
> ```

same Error : java.lang.NoSuchMethodError: No interface method startRestartGroup(ILjava/lang/String;)Landroidx/compose/runtime/Composer;

**Comment by skydoves** [comment]
I guess there is an official issue in [compose-beta07](https://developer.android.com/jetpack/androidx/releases/compose-ui#version_100_2).

> Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)

**Comment by masterofdaemon** [comment]
I guess so, your module is the only one custom that i've used, can you report this issue?

**Comment by wangchenyan** [comment]
I use [Google Accompanist](https://google.github.io/accompanist/coil/) instead

**Comment by skydoves** [comment]
@mrmans0n @masterofdaemon @wangchenyan 

Released a new version `1.2.2`.
And please check your compose-related dependencies version on your project, and update.

```gradle
composeVersion   : '1.0.0-beta07',
constraintVersion: '1.0.0-alpha07',
activityVersion  : '1.3.0-alpha08',
landscapistVersion : '1.2.2'
```

Thanks you for your issue :)
